### ISSUE TITLE
Importing data from a Dreamhost DB gets mangled

### ISSUE THREAD

**Issue by chrislloyd** [ricardochimal/taps#1]
I've been trying to import a DB from a pre-existing Dreamhost DB but the output gets all mangled with \10\11\15 etc.

Have a look at http://studio.heroku.com to see what I mean.

**Comment by chrislloyd** [comment]
So this isn't specific to Dreamhost at all, it's just converting all my nice Unix newlines into Windows ones and then serving them out as ugly \015\012's...

**Comment by ricardochimal** [comment]
update to taps 0.2.16, I think your problem is related to something I just fixed.

**Comment by chrislloyd** [comment]
Awesome, did fix. Thanks very much.
