### ISSUE TITLE
Ignores time zone when pulling from PostgreSQL to Sqlite

### ISSUE THREAD

**Issue by niho** [ricardochimal/taps#10]
I am trying to pull my database from Heroku (PostgreSQL) to my local dev machine (Sqlite) but the time zone on all datetime fields seems to be ignored.

So what is "Thu, 05 Nov 2009 14:05:34 UTC +00:00" on the Heroku side becomes "Thu, 05 Nov 2009 23:05:34 UTC +00:00" on my local machine, for example.

This is very annoying as I store files and images in S3 with timestamps in the path. Resulting in all images and files 404:ing on my development machine.

**Comment by DoppioJP** [comment]
Same happens to me when I try to push my local database to heroku, all the datetime data is shifted 8 hours back. I was trying to set TZ heroku config param, but it doesn't help. Is there anything in taps which forces shifting time?

**Comment by bigeasy** [comment]
Stuck on same problem. I'd like to be able to backup my Heroku databases to sqlite3 but the timezone problems make this unworkable.

**Comment by sutajio** [comment]
This work around should do the job:

$ TZ=America/Los_angeles heroku db:pull

**Comment by bigeasy** [comment]
I take it that I do the same thing if I ever go to restore the database with db:push, correct?

$ TZ=America/Los_angeles heroku db:push sqlite:///backups/backup.db --app myapp
