### ISSUE TITLE
Mishandles $ in username or password

### ISSUE THREAD

**Issue by atrophic** [ricardochimal/taps#11]
When pushing/pulling an exception is thrown as taps tries to access the database with a truncated username, ending where $ is found.  This happens even when the $ is escaped on the command line, or stored in an environment variable.  This is the top of the stack trace for the error, with a username of WebU$er

```
/usr/lib/ruby/gems/1.8/gems/activerecord-2.2.2/lib/active_record/connection_adapters/mysql_adapter.rb:548:in `real_connect': Access denied for user 'WebU'@'localhost' (using password: YES) (Mysql::Error)
```

**Comment by ricardochimal** [comment]
should be fine now I think.

**Comment by atrophic** [comment]
Thanks for the update. I like the other new features too (:
