### ISSUE TITLE
When I try to start taps server with --port option, I get "`server' was called incorrectly. Call as `server'"

### ISSUE THREAD

**Issue by TylerRick** [ricardochimal/taps#12]
<pre>
> taps server a b c --port 5001
`server' was called incorrectly. Call as `server'
</pre>

It works fine without the --port option.

What am I doing wrong?

And when I move the code from cli.rb to a cli.thor file to test it, it works fine there too:

<pre>
module Taps
class Cli < Thor
    desc "server <local_database_url> <login> <password>", "Start a taps database import/export server"
    method_options(:port => :numeric)
    def server(database_url, login, password)
          p options
    end
end
end
</pre>

<pre>
thor taps:cli:server a b c --port 3
{"port"=>3}
</pre>

<pre>
> which taps
/var/lib/gems/1.9.1/bin/taps

> ruby --version
ruby 1.9.1p243 (2009-07-16 revision 24175) [x86_64-linux]

> gem list thor
thor (0.11.5, 0.9.9)
> gem list taps
taps (0.2.23)
</pre>

**Comment by ricardochimal** [comment]
not using thor anymore, create a new issue if it's still happening
