### ISSUE TITLE
[warning] The response contained in an RestClient::Exception is now a RestClient::Response

### ISSUE THREAD

**Issue by ghost** [ricardochimal/taps#13]
Looks like there was a change in the RestClient exception API.

This is what I get when I heroku db:push (heroku 1.7.1, taps 0.2.24, rest-client 1.3.1):
[warning] The response contained in an RestClient::Exception is now a RestClient::Response instead of a Net::HTTPResponse, please update your code 
Taps Server Error: instance of Date needs to have method `marshal_load'

**Comment by ricardochimal** [comment]
fixed
