### ISSUE TITLE
uninitialized constant Mysql::Error

### ISSUE THREAD

**Issue by benjohnson77** [ricardochimal/taps#14]
I was able after some messing around to get the taps server command to run on ubuntu 9.10 running ruby 1.8. 

Now when I run this PULL command I get this error and I was wondering if its something I am doing wrong and how to find out. I really want to use taps for keeping a multiple dev environments in sync.

Here is the PULL command I am using
 sudo taps pull mysql://root@127.0.0.1:/lets_go_dev_trunk http://bjohnson:flexible@67.207.139.189:5000

And I get 

Failed to connect to database:
  NameError -> uninitialized constant Mysql::Error

I have standard mac ports mysql installation with blank password, and I can connect through client and ruby applications are running. 

Ben

**Comment by ricardochimal** [comment]
can you run  "gem list" and make sure that the mysql gem is installed? if it paste the output of gem list

**Comment by benjohnson77** [comment]
thank you for your help, here is my gem list

**\* LOCAL GEMS ***

actionmailer (2.3.4, 2.2.2, 1.3.6)
actionpack (2.3.4, 2.2.2, 1.13.6)
actionwebservice (1.2.6)
activerecord (2.3.4, 2.2.2, 1.15.6)
activeresource (2.3.4, 2.2.2)
activesupport (2.3.4, 2.2.2, 1.4.4)
acts_as_ferret (0.4.4, 0.4.3)
attributes (5.0.1)
bossman (0.4.1)
builder (2.1.2)
calendar_date_select (1.15)
cap-recipes (0.3.36)
capistrano (2.5.10, 2.5.9, 2.5.2)
capistrano-ext (1.2.1)
cgi_multipart_eof_fix (2.5.0)
cheat (1.2.1)
daemons (1.0.10)
dnssd (0.6.0)
fastthread (1.0.1)
fcgi (0.8.7)
ferret (0.11.6)
gem_plugin (0.2.3)
gemcutter (0.1.8)
git (1.2.5)
highline (1.5.1, 1.5.0)
hpricot (0.6.164)
json_pure (1.2.0)
libxml-ruby (1.1.2)
mime-types (1.16)
mongrel (1.1.5)
mysql (2.8.1)
needle (1.3.0)
net-scp (1.0.2, 1.0.1)
net-sftp (2.0.2, 2.0.1, 1.1.1)
net-ssh (2.0.15, 2.0.4, 1.1.4)
net-ssh-gateway (1.0.1, 1.0.0)
newrelic_rpm (2.9.8)
passenger (2.2.7)
prototype (2.0.0)
rack (1.0.1)
radiant (0.8.1)
rails (2.3.4, 2.2.2, 1.2.6)
rake (0.8.7, 0.8.3)
RedCloth (4.1.1)
rest-client (1.3.0, 1.2.0)
rmagick (2.12.2)
ruby-openid (2.1.7, 2.1.2)
ruby-yadis (0.3.4)
rubygems-update (1.3.5)
rubynode (0.1.5)
sequel (3.0.0)
sinatra (0.9.2)
sqlite3-ruby (1.2.4)
taps (0.2.24, 0.2.23)
termios (0.9.4)
thor (0.9.9)
xmpp4r (0.5, 0.4)

**Comment by benjohnson77** [comment]
Any idea what I might try?

**Comment by moviendome** [comment]
I don't know If we are the same problem but looking for this I've found your message.
I've testing Rails 3 pre and mysql gem didn't work for me.

After try a lot of things... I've solved the problem with this:

First, uninstalling & reinstalling the gem, now to work in x86_64. I don't know if this is your case:

sudo gem uninstall mysql
sudo env ARCHFLAGS="-arch x86_64" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config

Then adding this to the Gemfile

gem 'mysql', :bundle => false

Now, my rails application works fine with mysql

**Comment by ricardochimal** [comment]
There's no gemfile in this case, I'm trying to reproduce it the problem on my end

**Comment by ricardochimal** [comment]
Just thought of something, why are you using sudo? I think the mysql gem could be installed in your user's ~/.gem directory and not globally.  try taps db:pull without sudo  or do sudo gem install mysql

**Comment by benjohnson77** [comment]
i uninstalled mysql and then I reinstalled with the above command, maybe that wasn't the issue but mysql gem is in ~/.gem/ruby/1.8/gems/mysql2.8.1 blah blah, 

now when in I rant the taps pull command I get this.

benjohnson:letsgo_2.9 benjaminrjohnson99$ taps pull mysql://root:@127.0.0.1/lets_go_dev_trunk http://bjohnson:flexible@67.207.139.189:5000
Receiving schema
!!! Caught Server Exception
Taps Server Error: SQLite3::SQLException attempt to write a readonly database
benjohnson:letsgo_2.9 benjaminrjohnson99$ 

the great thing here is that I am actually connecting to the taps server. Just not able to complete the DB copy. Any ideas?

**Comment by ricardochimal** [comment]
sudo rm taps.db I think is your problem in this case, though you can also upgrade to the latest taps version which uses a Tempfile

**Comment by benjohnson77** [comment]
hope you don't mind the play by play, I did what you said, I updated the server and the client, now there is some magic happening but not quite success. 

benjohnson:letsgo_2.9 benjaminrjohnson99$ taps pull mysql://root:@127.0.0.1/lets_go_dev_trunk http://bjohnson:flexible@67.207.139.189:5000
Receiving schema
ruby: no such file to load -- ubygems (LoadError)
Receiving data
19 tables, 141,172 records
/Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:166:in `query': Mysql::Error Duplicate entry '1' for key 'PRIMARY' (Sequel::DatabaseError)
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:166:in`_execute'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:125:in `execute'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/connection_pool.rb:101:in`hold'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/database.rb:461:in `synchronize'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:125:in`execute'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/database.rb:296:in `execute_dui'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset.rb:276:in`execute_dui'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:365:in `execute_dui'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in`import'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in `each'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in`import'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:144:in `transaction'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/connection_pool.rb:108:in`hold'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/database.rb:461:in `synchronize'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:138:in`transaction'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in `import'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:212:in`cmd_receive_data'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:204:in `loop'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:204:in`cmd_receive_data'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:197:in `each'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:197:in`cmd_receive_data'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:176:in `cmd_receive'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:59:in`send'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:59:in `clientxfer'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:27:in`quickstart'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:21:in `start'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:26:in`quickstart'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:58:in `clientxfer'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:31:in`pull'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `send'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in`run'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor/task.rb:20:in `parse'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor.rb:78:in`start'
        from /Library/Ruby/Gems/1.8/gems/taps-0.2.25/bin/taps:13
        from /usr/bin/taps:19:in `load'
        from /usr/bin/taps:19
benjohnson:letsgo_2.9 benjaminrjohnson99$

**Comment by ricardochimal** [comment]
what does "schema dump mysql://root:@127.0.0.1/lets_go_dev_trunk"  produce?

also try dropping and recreating your local database first before you do "taps pull"

**Comment by benjohnson77** [comment]
benjohnson:taps benjaminrjohnson99$ schema dump mysql://root:@127.0.0.1/lets_go_dev_trunk
ActiveRecord::Schema.define do
  create_table "attractions", :force => true do |t|
    t.string   "name"
    t.string   "category"
    t.text     "description"
    t.integer  "budget"
    t.integer  "city_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "url"
    t.string   "phone"
    t.string   "dates"
    t.text     "address"
    t.boolean  "active",      :default => true
  end

# add_index "attractions", ["budget"], :name => "index_attractions_on_budget"

# add_index "attractions", ["city_id"], :name => "index_attractions_on_destination_id"

  create_table "attractions_stops", :id => false, :force => true do |t|
    t.integer "attraction_id"
    t.integer "stop_id"
  end

# add_index "attractions_stops", ["attraction_id"], :name => "index_attractions_stops_on_attraction_id"

# add_index "attractions_stops", ["stop_id"], :name => "index_attractions_stops_on_stop_id"

  create_table "chapters", :force => true do |t|
    t.string   "name"
    t.integer  "destination_id"
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

# add_index "chapters", ["destination_id"], :name => "index_chapters_on_destination_id"

  create_table "cities", :force => true do |t|
    t.string   "name"
    t.string   "essentials"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "comments", :force => true do |t|
    t.integer  "user_id"
    t.integer  "post_id"
    t.string   "name"
    t.string   "email"
    t.string   "website"
    t.text     "body"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "marked_spam", :default => false
    t.boolean  "reviewed",    :default => false
  end

  create_table "content_nodes", :force => true do |t|
    t.string   "name"
    t.text     "content"
    t.integer  "position"
    t.integer  "parent_id",      :default => 0,     :null => false
    t.integer  "chapter_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "dirty",          :default => false
    t.integer  "destination_id"
    t.integer  "seo_head_id"
  end

# add_index "content_nodes", ["chapter_id"], :name => "index_content_nodes_on_chapter_id"

# add_index "content_nodes", ["destination_id"], :name => "index_content_nodes_on_destination_id"

# add_index "content_nodes", ["parent_id"], :name => "index_content_nodes_on_parent_id"

# add_index "content_nodes", ["seo_head_id"], :name => "index_content_nodes_on_seo_head_id"

  create_table "destinations", :force => true do |t|
    t.string   "name"
    t.text     "essentials"
    t.text     "beyond_tourism"
    t.text     "discover"
    t.text     "book_intro"
    t.text     "facts_and_figures"
    t.text     "when_to_go"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "keyword"
    t.integer  "parent_id",            :default => 0,     :null => false
    t.integer  "redirect_to"
    t.integer  "sort_order",           :default => 999
    t.string   "flickr_id"
    t.string   "placement_id_728X90"
    t.string   "placement_id_160X600"
    t.string   "placement_id_300X250"
    t.boolean  "allow_post",           :default => false
  end

# add_index "destinations", ["parent_id"], :name => "index_destinations_on_parent_id"

  create_table "destinations_posts", :id => false, :force => true do |t|
    t.integer "destination_id"
    t.integer "post_id"
  end

# add_index "destinations_posts", ["destination_id"], :name => "idx_destination_id"

  create_table "destinations_users", :id => false, :force => true do |t|
    t.integer "destination_id"
    t.integer "user_id"
  end

# add_index "destinations_users", ["destination_id"], :name => "idx_destination_id"

  create_table "itineraries", :force => true do |t|
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "description"
    t.string   "title",       :default => "New Itinerary"
  end

# add_index "itineraries", ["user_id"], :name => "index_itineraries_on_user_id"

  create_table "letsgo_tripfilms_destinations", :force => true do |t|
    t.integer  "destination_id"
    t.integer  "tripfilms_destination_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

# add_index "letsgo_tripfilms_destinations", ["destination_id"], :name => "index_letsgo_tripfilms_destinations_on_destination_id", :unique => true

  create_table "post_attachments", :force => true do |t|
    t.integer  "post_id"
    t.integer  "user_id"
    t.integer  "width"
    t.integer  "height"
    t.integer  "size"
    t.string   "filename"
    t.string   "content_type"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "posts", :force => true do |t|
    t.string   "title"
    t.integer  "user_id"
    t.text     "body"
    t.text     "description"
    t.boolean  "draft",                      :default => true
    t.boolean  "reviewed",                   :default => true
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "category"
    t.string   "author",      :limit => 100
    t.boolean  "is_clone",                   :default => false
    t.boolean  "marked_spam",                :default => false
    t.integer  "edited_id"
  end

  create_table "schema_info", :id => false, :force => true do |t|
    t.integer "version"
  end

  create_table "seo_heads", :force => true do |t|
    t.string   "title"
    t.string   "description"
    t.text     "keywords"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "simple_captcha_data", :force => true do |t|
    t.string   "key",        :limit => 40
    t.string   "value",      :limit => 6
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "stops", :force => true do |t|
    t.integer  "city_id"
    t.integer  "itinerary_id"
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.text     "flights"
    t.text     "accommodations"
    t.text     "notes"
  end

# add_index "stops", ["city_id"], :name => "index_stops_on_destination_id"

# add_index "stops", ["itinerary_id"], :name => "index_stops_on_itinerary_id"

  create_table "user_pics", :force => true do |t|
    t.integer  "parent_id"
    t.integer  "user_id"
    t.integer  "width"
    t.integer  "height"
    t.integer  "size"
    t.string   "filename"
    t.string   "thumbnail"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.string   "first_name"
    t.string   "last_name"
    t.string   "email"
    t.string   "username"
    t.string   "salt"
    t.string   "salted_password"
    t.string   "address"
    t.string   "address_two"
    t.string   "city"
    t.string   "state"
    t.string   "zip_code"
    t.string   "country"
    t.string   "phone_number"
    t.string   "website"
    t.boolean  "change_password",     :default => false
    t.boolean  "suspended",           :default => false
    t.boolean  "review_all",          :default => true
    t.date     "birthday"
    t.datetime "last_login"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "admin"
    t.boolean  "editor"
    t.boolean  "writer"
    t.string   "title"
    t.string   "company"
    t.text     "bio"
    t.boolean  "blogger"
    t.boolean  "partner"
    t.boolean  "marked_spam",         :default => false
    t.string   "reset_password_code"
  end

# add_index "users", ["email"], :name => "index_users_on_email"

end

**Comment by ricardochimal** [comment]
do you have anything in your RUBYOPT environment variable?  echo $RUBYOPT

also, did dropping the database and creating it again let you get further in the db transfer?

**Comment by benjohnson77** [comment]
echo $RUBYOPT
rubygems

**Comment by benjohnson77** [comment]
benjohnson:~ benjaminrjohnson99$ taps pull mysql://root:@127.0.0.1/lets_go_dev_trunk http://bjohnson:flexible@67.207.139.189:5000
Receiving schema
ruby: no such file to load -- ubygems (LoadError)
Receiving data
19 tables, 141,173 records
/Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:166:in `query': Mysql::Error Table 'lets_go_dev_trunk.destinations_users' doesn't exist (Sequel::DatabaseError)
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:166:in`_execute'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:125:in `execute'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/connection_pool.rb:101:in`hold'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/database.rb:461:in `synchronize'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:125:in`execute'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/database.rb:296:in `execute_dui'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset.rb:276:in`execute_dui'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:365:in `execute_dui'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in`import'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in `each'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in`import'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:144:in `transaction'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/connection_pool.rb:108:in`hold'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/database.rb:461:in `synchronize'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/adapters/mysql.rb:138:in`transaction'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/dataset/convenience.rb:126:in `import'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:212:in`cmd_receive_data'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:204:in `loop'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:204:in`cmd_receive_data'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:197:in `each'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:197:in`cmd_receive_data'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:176:in `cmd_receive'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:59:in`send'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:59:in `clientxfer'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:27:in`quickstart'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:21:in `start'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/client_session.rb:26:in`quickstart'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:58:in `clientxfer'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/../lib/taps/cli.rb:31:in`pull'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in `send'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor/task.rb:27:in`run'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor/task.rb:20:in `parse'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/thor-0.9.9/lib/thor.rb:78:in`start'
        from /Users/benjaminrjohnson99/.gem/ruby/1.8/gems/taps-0.2.25/bin/taps:13
        from /usr/bin/taps:19:in `load'
        from /usr/bin/taps:19
benjohnson:~ benjaminrjohnson99$

**Comment by ricardochimal** [comment]
your RUBYOPT is wrong, it should be set to "-r rubygems"

try that and then try the pull again

**Comment by afzallakdawala** [comment]
Null error :

/home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in `exec': PG::Error: ERROR:  null value in column "agent_paid_date" violates not-null constraint (Sequel::DatabaseError)
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in`block (2 levels) in execute'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/logging.rb:28:in `log_yield'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in`block in execute'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:158:in `check_disconnect_errors'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:175:in`execute'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:240:in `block (2 levels) in execute'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/connection_pool/threaded.rb:71:in`hold'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/connecting.rb:226:in `synchronize'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:240:in`block in execute'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:261:in `check_database_errors'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/adapters/postgres.rb:238:in`execute'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/query.rb:71:in `execute_dui'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:552:in`execute_dui'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in `block (2 levels) in import'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in`each'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in `block in import'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/query.rb:223:in`_transaction'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/query.rb:209:in `block in transaction'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/connection_pool/threaded.rb:84:in`hold'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/connecting.rb:226:in `synchronize'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/database/query.rb:207:in`transaction'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/sequel-3.20.0/lib/sequel/dataset/actions.rb:243:in `import'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/data_stream.rb:315:in`import_rows'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/data_stream.rb:142:in `fetch_remote'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:308:in`block in pull_data_from_table'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:301:in `loop'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:301:in`pull_data_from_table'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:284:in `block in pull_data'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:278:in`each'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:278:in `pull_data'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:253:in`block in run'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:203:in `call'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:203:in`catch_errors'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/operation.rb:246:in `run'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/cli.rb:172:in`clientxfer'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/cli.rb:39:in `pull'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/lib/taps/cli.rb:27:in`run'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/gems/taps-0.3.24/bin/taps:6:in `<top (required)>'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/taps:23:in`load'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/taps:23:in `<main>'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in`eval'
    from /home/afzal/.rvm/gems/ruby-1.9.3-p429/bin/ruby_noexec_wrapper:14:in `<main>'
