### ISSUE TITLE
Requires ActiveRecord 2.2.2

### ISSUE THREAD

**Issue by hone** [ricardochimal/taps#16]
I'm currently using AR 2.3.2 on a project and am running issues using taps in a bundle:

No compatible versions could be found for required dependencies:
    Conflict on: "activerecord":
    \* activerecord (2.2.2) activated by taps (= 0.2.26, runtime)
    \* activerecord (= 2.3.2, runtime) required by rails (= 2.3.2, runtime)
    All possible versions of origin requirements conflict.

Is there a reason that taps is married to 2.2.2?  Can we use ~> instead of = ?

**Comment by ricardochimal** [comment]
The main reason is that I have not tested any of the patches that I use for newer versions of activerecord.  I'm actually doing away with activerecord altogether so if you want to give it a shot my master branch uses only the sequel gem for database operations.

**Comment by hone** [comment]
yeah, I just saw that. going to try out the master branch.  I'll let you know how it works.

**Comment by hone** [comment]
hmm, running into conflicts on requiring rack 1.1.0.
