### ISSUE TITLE
MySQL varchar as id/primary key fails

### ISSUE THREAD

**Issue by titanous** [ricardochimal/taps#17]
When trying to pull a MySQL db that has a id column that is a varchar and primary key, the destination db gets id set to integer causing type mismatch failures:

```
PGError ERROR:  invalid input syntax for integer: "OK" (Sequel::DatabaseError)
LINE 1: INSERT INTO "test" ("id") VALUES ('OK')

SQLite3::SQLException datatype mismatch (Sequel::DatabaseError)
```

**Comment by ricardochimal** [comment]
does this happen in taps 0.3.0.pre10  ?

**Comment by titanous** [comment]
No, seems to work fine. I'm going to open a ticket for a different issue with the pre version.
