### ISSUE TITLE
UTF8 error in 0.3.0pre10

### ISSUE THREAD

**Issue by titanous** [ricardochimal/taps#18]
I'm not sure whether this one is taps or my data, but mysql2psql works fine, so I'm thinking it's taps. Linked below is a SQL dump of the MySQL database that I'm trying to convert to PostgreSQL. This is the output of taps 0.3.0pre10:

```
Receiving schema
Receiving data
7 tables, 30,270 records
compliance_ca: 100% |==========================================| Time: 00:00:00
inspections:   100% |==========================================| Time: 00:00:08
facilities:    100% |==========================================| Time: 00:00:02
/Users/titanous/.rvm/gems/ree-1.8.7-2010.01/gems/sequel-3.10.0/lib/sequel/adapters/postgres.rb:163:in `async_exec': PGError: ERROR:  invalid byte sequence for encoding "UTF8": 0xb0 (Sequel::DatabaseError)
HINT:  This error can also happen if the byte sequence does not match the encoding expected by the server, which is controlled by "client_encoding".
```

  mysql  Ver 14.14 Distrib 5.1.45
  psql (PostgreSQL) 8.4.3

http://titanous.com/files/eatsafe.tbz

**Comment by ricardochimal** [comment]
how are you calling taps?

the db url should contain an encoding argument like  mysql://root@localhost/mydb?encoding=utf8

**Comment by titanous** [comment]
Okay, the encoding=utf8 fixed this issue. Now I'm getting this:

Server:
    ArgumentError - comparison of Symbol with 0 failed:
    !! Unexpected error while processing request: comparison of Symbol with 0 failed

Client:
    Receiving schema
    Receiving data
    7 tables, 30,270 records
    comments:      100% |==========================================| Time: 00:00:00
    compliance_ca: 100% |==========================================| Time: 00:00:00
    compliance_de: 100% |==========================================| Time: 00:00:00
    compliance_re: 100% |==========================================| Time: 00:00:00
    facilities:    100% |==========================================| Time: 00:00:01
    inspections:   100% |==========================================| Time: 00:00:18
    Saving session to pull_201004122307.dat..                      | ETA:  --:--:--
    !!! Caught Server Exception
    HTTP CODE:

**Comment by titanous** [comment]
Oops, so that was ruby 1.9.1. Works fine on 1.8.7.

**Comment by metaskills** [comment]
Was having this issue too. Adding "?encoding=utf8" to both sides (the mysql/postgresql urls) worked great. Also had to properly quote the argument in my console too.
