### ISSUE TITLE
PGError ERROR:  invalid input syntax for integer

### ISSUE THREAD

**Issue by snoblenet** [ricardochimal/taps#19]
I received the above message after executing an add-column-to-table migration in Heroku.

At that point, my app was broken, and the only fix was to heroku rake db:reset, which is drastic.

I didn't have the presence of mind to save Heroku's logs, and Heroku doesn't save them itself, so I don't have much to add. However, I believe the issue related to my use of friendly_id, which executes some integer-to-string-and-back magic to allow you have strings in your URLs.

I say this because Andy Shipman has reported a remarkably similar experience in Heroku's Google Group, and luckily provided more information than I was able to:

http://groups.google.com/group/heroku/browse_thread/thread/f5f3e807dfe7c859# 

The table to which I was adding a column was a table directly affected by friendly_id.

I spotted this error in my Heroku Logs while Andy saw it in the console when pushing the app, but it's the same basic idea.

**Comment by titanous** [comment]
This issue is fixed in 0.3.0pre10, and from what I've heard, it should be released today, and hopefully updated on Heroku's end as well.

**Comment by snoblenet** [comment]
Cheers. I'll look out for it.
