### ISSUE TITLE
Error - SQLite3::SQLException unrecognized token

### ISSUE THREAD

**Issue by ghost** [ricardochimal/taps#2]
Installed taps on RHEL 4 and it errors out when I try to start the server:

http://gist.github.com/103544

Starts just fine on my local OS X box.

**Comment by ricardochimal** [comment]
any weird characters in your username or password?

**Comment by nonfiction** [comment]
none at all - here's another try, new db, new username, new password as simple as possible:

http://gist.github.com/103881

This db was just created for this purpose, have verified the username and password - it's all standard stuff AFAIK.

MySQL 5.0.22

**Comment by ricardochimal** [comment]
what version of ruby? Anything less than 1.8.5 or 1.8.6 may not work properly.

**Comment by nonfiction** [comment]
There we go - it's 1.8.4.

I'll try and upgrade and see if that helps.

**Comment by nonfiction** [comment]
Same error with 1.8.6 - I also removed and re-installed taps:

[darron@ginaz i386]$ whereis ruby
ruby: /usr/bin/ruby /usr/lib/ruby /usr/share/man/man1/ruby.1.gz
[darron@ginaz i386]$ /usr/bin/ruby -v
ruby 1.8.6 (2008-08-11 patchlevel 287) [i386-linux]

**Comment by ricardochimal** [comment]
hmm what version of the sqlite3 library do you have installed?

**Comment by nonfiction** [comment]
It's 3.1.2 - that's the last version for RHEL 4 from ATRPMS - I'll update and try - I'm not using it anywhere anyways.
