### ISSUE TITLE
comparison of Symbol with 0 failed (ArgumentError) 

### ISSUE THREAD

**Issue by vkryukov** [ricardochimal/taps#20]
Hello,

when I'm trying to push my database to heroku with 

heroku db:push 

after doing 

heroku db:reset

I get the following error:

XXXX victor$ heroku db:push
Loaded Taps v0.3.0
Auto-detected local database: postgres://victor@127.0.0.1/XXXX?encoding=utf8
Sending schema
Sending data
4 tables, 170,276 records
schema_migrat: 100% |==========================================| Time: 00:00:01
/opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:258:in `>': comparison of Symbol with 0 failed (ArgumentError)
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:258:in`block (2 levels) in load_buffer'
    from /opt/local/lib/ruby/gems/1.9.1/gems/sequel-3.10.0/lib/sequel/core.rb:249:in `instance_eval'
    from /opt/local/lib/ruby/gems/1.9.1/gems/sequel-3.10.0/lib/sequel/core.rb:249:in`virtual_row'
    from /opt/local/lib/ruby/gems/1.9.1/gems/sequel-3.10.0/lib/sequel/dataset/query.rb:410:in `filter_expr'
    from /opt/local/lib/ruby/gems/1.9.1/gems/sequel-3.10.0/lib/sequel/dataset/query.rb:379:in`_filter'
    from /opt/local/lib/ruby/gems/1.9.1/gems/sequel-3.10.0/lib/sequel/dataset/query.rb:105:in `filter'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:258:in`block in load_buffer'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:253:in `loop'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:253:in`load_buffer'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:273:in `fetch_buffered'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:289:in`fetch_rows'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/data_stream.rb:107:in `fetch'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:469:in`block (2 levels) in push_data_from_table'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/utils.rb:78:in `calculate_chunksize'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:467:in`block in push_data_from_table'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:459:in `loop'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:459:in`push_data_from_table'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:454:in `block in push_data'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:449:in`each'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:449:in `push_data'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/operation.rb:384:in`run'
    from /opt/local/lib/ruby/gems/1.9.1/gems/taps-0.3.0/lib/taps/cli.rb:159:in `clientxfer'
    from /opt/local/lib/ruby/gems/1.9.1/gems/heroku-1.9.0/lib/heroku/commands/db.rb:147:in`taps_client'
    from /opt/local/lib/ruby/gems/1.9.1/gems/heroku-1.9.0/lib/heroku/commands/db.rb:20:in `push'
    from /opt/local/lib/ruby/gems/1.9.1/gems/heroku-1.9.0/lib/heroku/command.rb:48:in`run_internal'
    from /opt/local/lib/ruby/gems/1.9.1/gems/heroku-1.9.0/lib/heroku/command.rb:20:in `run'
    from /opt/local/lib/ruby/gems/1.9.1/gems/heroku-1.9.0/bin/heroku:14:in`<top (required)>'
    from /opt/local/bin/heroku:19:in `load'
    from /opt/local/bin/heroku:19:in`<main>'

**Comment by ricardochimal** [comment]
try it with ruby 1.8.6 or ruby 1.8.7.   1.9.x doesn't work right now

**Comment by vkryukov** [comment]
Thanks Ricardo. Do you have any timeline for when 1.9.x will be supported? My code has some 1.9.x dependencies already - not that's it's impossible to change, but I'd like to run under 1.9.1.

**Comment by ricardochimal** [comment]
not sure yet but it's on my list of things to do for at least 0.4 but not sure if it'll go in 0.3.x.  got any good pointers to common changes in 1.9.1 ?  1.9.2 seems like it'll change a lot of things as well so I'm kind of on the fence about which 1.9.x to go for.

**Comment by vkryukov** [comment]
What about http://svn.ruby-lang.org/repos/ruby/trunk/NEWS? Doesn't look like it'll have many user-visible changes between 1.9.1 and 1.9.2, but I may be missing something...

**Comment by vkryukov** [comment]
Maybe you could you provide some pointers to which parts of code may be 1.8.x-dependent?

**Comment by vkryukov** [comment]
OK, I found a solution! 

This problem is related to the fact that Ruby 1.9 defines  [], <, <=, >, and >= for Symbol, and Sequel does not redefine this method if they are already defined. (see here: http://sequel.rubyforge.org/rdoc/files/doc/release_notes/2_10_0_txt.html).

The solution, therefore, is to change line #258 to (notice key.sql_number):

ds = table.order(*order_by).filter { key.sql_number > buf_limit }.limit(limit)

If you could please check whether it still passes the tests for 1.8.6&1.8.7? I have no problems with my 1.9.1 installation now, and in fact I just finished importing my database.

Thank you very much for working on Tags!

**Comment by ricardochimal** [comment]
taps 0.3.1 should include your fix
