### ISSUE TITLE
0.3.2 heroku db:pull throws duplicate key value errors

### ISSUE THREAD

**Issue by cuzic4n** [ricardochimal/taps#22]
did a heroku db:pull .. all good.. then upgraded to the latest heroku gem and taps gem.. did a db:pull and got a bunch of errors..
i.e.
/Ruby/lib/ruby/gems/1.8/gems/sequel-3.10.0/lib/sequel/adapters/postgres.rb:163:in `async_exec': PGError: ERROR:  duplicate key v
alue violates unique constraint "cities_pkey" (Sequel::DatabaseError)

went into pgadmin and deleted all the tables and did a heroku db:pull and all was well..
ran heroku db:pull again and got the same errors since the tables already existed.

i went from 1.8.0 to 1.9.1
$ gem list|grep heroku
heroku (1.9.1, 1.8.0)

and for taps.. 0.2.25 to 0.3.2
$ gem list|grep taps
taps (0.3.2, 0.2.25)

I posted this issue on heroku github as well since I am not sure the exact source of the issue and the gems are dependent so I cannot downgrade just taps and try..

**Comment by ricardochimal** [comment]
It's taps, the behavior you want is a side effect of using the activerecord schema loader in 0.2.x.  I'll see about duplicating this in 0.3.x, I didn't think it was all that great originally because it wipes out your schema as a side effect with no warnings/errors.

**Comment by ricardochimal** [comment]
I made a few quick fixes, try taps 0.3.3.  keep in mind that there is no going back when you drop the table(s)

**Comment by cuzic4n** [comment]
yeah that 'fixed' it.. took it back to how it used to behave..

**Comment by sleepycat** [comment]
I just ran "sudo gem update" and tried a push. Its still a problem here:

Saving session to push_201004222056.dat..                                                                                                                    | ETA:  --:--:--
!!! Caught Server Exception
HTTP CODE: 500
Taps Server Error: PGError: ERROR:  duplicate key value violates unique constraint "config_pkey"

**Comment by ricardochimal** [comment]
what taps version?

**Comment by sleepycat** [comment]
0.3.3.

**Comment by ricardochimal** [comment]
is it on heroku? if so open a support request on support.heroku.com

**Comment by sleepycat** [comment]
It is on heroku actually. I have an existing ticket (#5845) that is being effected by this issue.
