### ISSUE TITLE
json_pure dependency in Heroku/Taps

### ISSUE THREAD

**Issue by greenplastik** [ricardochimal/taps#23]
Both Heroku and Taps have their json_depency set as ~> 1.2.4. The current version of json/json_pure 1.4.0

No other gems have the older version requirement and several gems are pushing me to version 1.4.0

As a result, I get the expected errors about not being able to load json_pure 1.2.4 for heroku or taps, because version 1.4.0 has already loaded.

Please advise. Thank you.

-A.

**Comment by mgomes** [comment]
This issue seems to also have led to a regression. I get the following error when attempting a `heroku db:push`

`taps-0.3.3/lib/taps/operation.rb:483:in 'to_json': uninitialized constant JSON::SAFE_STATE_PROTOTYPE (NameError)`

Uninstalling json 1.4.0 seems to have fixed it.

**Comment by greenplastik** [comment]
agreed. i had to uninstall json 1.4.0 and json_pure 1.4.0 and then specifically specify the version of taps and heroku in my bundler gemfile.

**Comment by ricardochimal** [comment]
tracked it down to a problem with gemcutter rubygems plugin, it requires json >= 0 so rubygems loads it first before it loads taps and then you get into a messed up situation.  taps 0.3.4 should solve it, also update your heroku gem if you're using that too.

**Comment by sandipransing** [comment]
looks like there is an issue with taps version
gist http://gist.github.com/1054026
