### ISSUE TITLE
Time out of range

### ISSUE THREAD

**Issue by dfens** [ricardochimal/taps#24]
While importing database in the beginning everything is ok, but in the moment I see error

Error encountered loading data, wrote the data chunk to dump.4096.dat                                                                                              | ETA:  --:--:--
/usr/lib/ruby/gems/1.8/gems/taps-0.3.4/lib/taps/data_stream.rb:183:in `_load': time out of range (ArgumentError)

**Comment by ricardochimal** [comment]
try taps 0.3.6, should fix it.
