### ISSUE TITLE
Pushing data with index first

### ISSUE THREAD

**Issue by paramaw** [ricardochimal/taps#26]
Hi there,
I'm trying to push to heroku, and it fails when I'm pushing 5 Gigs of data. The data is capable of being uploaded, but it's not able to push the index due to the 30 seconds restriction.

Would it be possible to push the index first, and data later so that it doesn't fail.

Thanks

**Comment by ricardochimal** [comment]
I added the option in taps v0.3.5 and heroku v1.9.9 defaults to sending the indexes first

**Comment by paramaw** [comment]
Thanks :)

**Comment by paramaw** [comment]
Awesome
