### ISSUE TITLE
read-only server?

### ISSUE THREAD

**Issue by seamusabshere** [ricardochimal/taps#27]
hi,

Is it possible to disallow pushes?

Thanks!
Seamus

**Comment by ricardochimal** [comment]
you could set it up behind nginx and catch anything doing /sessions/(\d+)/push*

I'm willing to consider accepting a patch to taps but to be honest i'm not sure how I feel about it

**Comment by seamusabshere** [comment]
hi,

Thanks for the tip! EngineYard put this in place for us:

<pre>
upstream taps {
  server localhost:5000;
}

server {
  listen 5001;
  location / {
  if ($request_filename !~ /sessions/(\d+)/push.*) {
    proxy_pass http://taps;
  }
  }
}
</pre>


Best,
Seamus

**Comment by seamusabshere** [comment]
Here's how to do it in Apache 2.2:

```
# make sure to enable mod_proxy and mod_proxy_http
Listen 5000
<VirtualHost _default_:5000>
  ServerName data.brighterplanet.com
  CustomLog /var/log/apache2/taps_proxy.access.log combined
  ProxyPass / http://127.0.0.1:4999/
  # allow most requests...
  <Location />
    Order Deny,Allow
    Allow from all
  </Location>
  # ... but deny any request containing "push"
  <LocationMatch push>
    Order Allow,Deny
    Deny from all
  </LocationMatch>
</VirtualHost>
```
