### ISSUE TITLE
got RestClient::RequestFailed: HTTP status code 502 when pushing large data

### ISSUE THREAD

**Issue by paramaw** [ricardochimal/taps#29]
Hi there,

I was doing heroku db:push --tables sometables on a 2 gigabyte table.
It went on to work for about a couple hours, and then it failed, with a caught server exception 502.

I tried to do a resume, but it gave me RestClient::RequestFailed: HTTP status code 502
Finally I tried to just re ran that first command heroku db:push --tables sometables
and it gave me the same error: RestClient::RequestFailed: HTTP status code 502

Thanks,

Parama

**Comment by ricardochimal** [comment]
please submit a ticket to heroku @ http://support.heroku.com for better assistance w/ heroku+taps
