### ISSUE TITLE
Installing rack 1.0.0 breaks everything

### ISSUE THREAD

**Issue by skammer** [ricardochimal/taps#3]
Installing rack 1.0.0 breaks current sinatra (0.9.1.1). To fix it I installed sinatra-sinatra gem (which is basically sinatra 0.9.1.3).
Latest sinatra breaks taps 0.2.16 (it depends on 'sinatra', '~> 0.9.0'). So, things get pretty complicated.

**Comment by ricardochimal** [comment]
sinatra 0.9.1.1 gemspec indicates that it should be using rack less than 1.0.0.
I think this might be a problem with sinatra, I'll check it out and forward it to Blake Blake Mizerany.

**Comment by ricardochimal** [comment]
updated gem should depend on a newer sinatra that doesn't have this problem.
