### ISSUE TITLE
Taps fails on windows xp if ruby is installed in directory with a space in its name

### ISSUE THREAD

**Issue by kammerer** [ricardochimal/taps#31]
I have ruby installed in C:\Program Files\Ruby. When I try to run push or pull (with heroku) I get following output:

> H:\work\www\rails\cookbook>heroku db:pull
> Loaded Taps v0.3.4
> Auto-detected local database: postgres://cookbook:xxx@localhost:5432/cookbook_devel?encoding=utf8
> Warning: Data in the database 'postgres://cookbook:xxx@localhost:5432/cookbook_devel?encoding=utf8' will be overwritten and will not be recoverable.
> Are you sure you wish to continue? (y/n)? y
> Receiving schema
> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.
> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.
> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.
> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.
> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.
> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.
> (...)
> Receiving data
> 13 tables, 177 records
> (...)

The message

> Nazwa 'C:/program' nie jest rozpoznawana jako polecenie wewnętrzne lub zewnętrzne, program wykonywalny lub plik wsadowy.

is standard Win XP message meaning that an executable ('C:/program' in this case) can not be found.

The problem lies in `Taps::Utils.schema_bin(*args)` which tries to execute invalid command. Executed command should be enclosed in parentheses, somewhat like this:

  `"#{File.dirname(__FILE__)}/../../bin/#{bin('schema')}" #{args.map { |a| "'#{a}'" }.join(' ')}`

**Comment by ricardochimal** [comment]
should be fixed in the github repo now
