### ISSUE TITLE
utils.rb schema_bin doesn't properly escape Windows filespecs with embedded spaces

### ISSUE THREAD

**Issue by jds13** [ricardochimal/taps#35]
schema_bin wasn't properly escaping filenames with embedded spaces:
   Sending schema
   'c:/program' is not recognized as an internal or external command,TA:  --:--:--
operable program or batch file.
   'c:/program' is not recognized as an internal or external command,TA:  00:00:17
operable program or batch file.
   ...

This change to utils.rb:125 in ricardochimal-taps-v0.3.6-1-g9141fbe.zip fixed it:
  def schema_bin(*args)
      # `#{File.dirname(__FILE__)}/../../bin/#{bin('schema')} #{args.map { |a| "'#{a}'" }.join(' ')}`
           File.dirname(**FILE**)+'/../../bin/'+bin('schema')+' '+args.map { |a| "'#{a}'" }.join(' ')
   end

**Comment by ricardochimal** [comment]
http://github.com/ricardochimal/taps/commit/9141fbe8d2e3eb58f49d0c725ab36d768d239730   can you make this change to taps version and see if it fixes it? your change looks like it simply skips running bin/schema

**Comment by ricardochimal** [comment]
try 0.3.9
