### ISSUE TITLE
Sequel 3.12.0 encoding problems

### ISSUE THREAD

**Issue by chipiga** [ricardochimal/taps#37]
Sequel 3.12.0 have problem with encodings
http://code.google.com/p/ruby-sequel/issues/detail?id=300&can=1&start=200#c10
Is it possible revert taps dependency to previous sequel gem?

**Comment by ricardochimal** [comment]
The sequel maintainer says that sequel 3.12.1 will be released soon with a fix to your problem.

**Comment by ricardochimal** [comment]
you should be able to update to taps 0.3.9 which should pull in sequel 3.12.1.
