### ISSUE TITLE
pull exception with 0.3.7 and 0.3.8

### ISSUE THREAD

**Issue by jonforums** [ricardochimal/taps#38]
On a Win7 system using either 1.8.7p249 or 1.9.1p378 from http://rubyinstaller.org/ I get the following exception used with heroku. Previous version of Taps worked fine with 1.8.7p249 so it appears something new in 0.3.7 is causing the exception.

While it appears the issue is Taps-specific I'm not clear whether it may be the heroku gem. I originally posted to http://groups.google.com/group/heroku/browse_thread/thread/15526a6563b4096c with no response yet.

I haven't looked at Taps "schema.cmd" yet for any arg passing issues...no spaces in any of the involved paths.

C:\Users\Jon\Documents\WebDev\rubyinstaller.heroku.com>heroku db:pull sqlite://app-backup.db
Loaded Taps v0.3.8
Warning: Data in the database 'sqlite://app-backup.db' will be overwritten and will not be recoverable.
Are you sure you wish to continue? (y/n)? y
Receiving schema
c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/utils.rb:126:in ``': No such file or directory - 'c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/bin/schema.cmd' 'load'
'sqlite://app-backup.db' 'C:/Users/Jon/AppData/Local/Temp/taps20100604-3656-73b1ct-0'
(Errno::ENOENT)
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/utils.rb:126:in`sc
hema_bin'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/utils.rb:113:in `lo
ad_schema'
        from c:/ruby187/lib/ruby/1.8/tempfile.rb:188:in`open'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/utils.rb:111:in `lo
ad_schema'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/operation.rb:244:in
`pull_schema'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/operation.rb:242:in
 `each'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/operation.rb:242:in
`pull_schema'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/operation.rb:216:in
 `run'
        from c:/ruby187/lib/ruby/gems/1.8/gems/taps-0.3.8/lib/taps/cli.rb:164:in`clie
ntxfer'
        from c:/ruby187/lib/ruby/gems/1.8/gems/heroku-1.9.9/lib/heroku/commands/db.rb:
151:in `taps_client'
        from c:/ruby187/lib/ruby/gems/1.8/gems/heroku-1.9.9/lib/heroku/commands/db.rb:
23:in`pull'
        from c:/ruby187/lib/ruby/gems/1.8/gems/heroku-1.9.9/lib/heroku/command.rb:48:i
n `send'
        from c:/ruby187/lib/ruby/gems/1.8/gems/heroku-1.9.9/lib/heroku/command.rb:48:i
n`run_internal'
        from c:/ruby187/lib/ruby/gems/1.8/gems/heroku-1.9.9/lib/heroku/command.rb:20:i
n `run'
        from c:/ruby187/lib/ruby/gems/1.8/gems/heroku-1.9.9/bin/heroku:13
        from c:/ruby187/bin/heroku:19:in`load'
        from c:/ruby187/bin/heroku:19

**Comment by ricardochimal** [comment]
If you can create a patch and send me a pull request I'll be happy to get that fixed.  I don't have a windows machine so it's not easy for me

**Comment by ricardochimal** [comment]
try taps 0.3.9, I had someone test on windows and it seemed to work fine.

**Comment by jonforums** [comment]
I'm away from my Win7 with 1.8.7p249 machine that exhibited this bug but I'll try it tomorrow and post back.

FYI, on Win7 with 1.9.1p378 from http://rubyinstaller.org/ I get the following error after taps appeared to have downloaded most of the data. This is a separate issue I know and I'll post it as such after I've done a bit more investigation...such as reading your docs to see if taps is even meant to work on 1.9.x ;)

Thanks, Jon

Error encountered loading data, wrote the data chunk to dump.3944.dat
D:/Ruby191/lib/ruby/gems/1.9.1/gems/taps-0.3.9/lib/taps/data_stream.rb:187:in `load': class DateTime needs to have method`_load' (TypeError)

**Comment by ricardochimal** [comment]
yeah taps currently does not work with ruby 1.9.x.  a work around is to use ruby 1.8.7.

**Comment by jonforums** [comment]
0.3.9 fixes the the issue for meon 1.8.7p249 on my Win7 box.

Thank you for the quick turnaround considering you don't have a Windows dev machine!!
