### ISSUE TITLE
Where do I get the C-based adadpter?

### ISSUE THREAD

**Issue by lsiden** [ricardochimal/taps#47]
heroku db:pull mysql://root:r00t@localhost/busbingo
Loaded Taps v0.3.11
Warning: Data in the database 'mysql://root:r00t@localhost/busbingo' will be overwritten and will not be recoverable.
Are you sure you wish to continue? (y/n)? y
Failed to connect to database:
  Sequel::AdapterNotFound -> LoadError: require 'mysql' did not define Mysql::CLIENT_MULTI_RESULTS!
  You are probably using the pure ruby mysql.rb driver,
  which Sequel does not support. You need to install
  the C based adapter, and make sure that the mysql.so
  file is loaded instead of the mysql.rb file.

Where do I get the C-based adapter.  What is it called?

**Comment by mattfawcett** [comment]
The rubygem is called mysql - `gem install mysql`

**Comment by ricardochimal** [comment]
yep what mattfawcett said is correct

**Comment by lsiden** [comment]
With Ruby 1.9.1 and mysql:  heroku db:pull mysql://root:r00t@localhost/busbingo

Error encountered loading data, wrote the data chunk to dump.28345.dat                                             | ETA:  --:--:--
/home/lsiden/.rvm/gems/ruby-1.9.1-p378/gems/taps-0.3.11/lib/taps/data_stream.rb:190:in `load': class DateTime needs to have method`_load' (TypeError)
    from /home/lsiden/.rvm/gems/ruby-1.9.1-p378/gems/taps-0.3.11/lib/taps/data_stream.rb:190:in `parse_encoded_data'
    from /home/lsiden/.rvm/gems/ruby-1.9.1-p378/gems/taps-0.3.11/lib/taps/data_stream.rb:133:in`fetch_remote'
    from /home/lsiden/.rvm/gems/ruby-1.9.1-p378/gems/taps-0.3.11/lib/taps/operation.rb:287:in `block in pull_data_from_table'

With Ruby 1.8.7: 

heroku db:pull mysql://root:r00t@localhost/busbingo
Loaded Taps v0.3.11
Warning: Data in the database 'mysql://root:r00t@localhost/busbingo' will be overwritten and will not be recoverable.
Are you sure you wish to continue? (y/n)? y
Failed to connect to database:
  Sequel::AdapterNotFound -> LoadError: require 'mysql' did not define Mysql::CLIENT_MULTI_RESULTS!
  You are probably using the pure ruby mysql.rb driver,
  which Sequel does not support. You need to install
  the C based adapter, and make sure that the mysql.so
  file is loaded instead of the mysql.rb file.

Also have problems in 1.8.7 and 1.8.1 if I try pulling it into a SqlLite database.

C'mon, there has to be a way to get my data out!

Tell me if there is anything else I can give you that might help.

**Comment by ricardochimal** [comment]
use ruby 1.8.7 not 1.9.1

You need to install the mysql gem for ruby 1.8.7

**Comment by lsiden** [comment]
Just tried that.  Please see output at http://pastie.org/1138561/

**Comment by ricardochimal** [comment]
From looking at that output I think somehow you may have compiled the mysql gem for 1.9.1 but it's loading in 1.8.7.  rvm use 1.8.7, open up a new terminal, uninstall the mysql gem, and install the mysql gem again.

**Comment by ddollar** [comment]
If you're on Snow Leopard, you can solve this with:

env ARCHFLAGS="-arch x86_64" gem install mysql

**Comment by andrewkolesnikov** [comment]
Mine is broken like that as well.

ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]

**Comment by densone** [comment]
Same error for me: 
I am running Snow Leopard MySQL 5.5

Failed to connect to database:
  Sequel::AdapterNotFound -> LoadError: require 'mysql' did not define Mysql::CLIENT_MULTI_RESULTS!
  You are probably using the pure ruby mysql.rb driver,
  which Sequel does not support. You need to install
  the C based adapter, and make sure that the mysql.so
  file is loaded instead of the mysql.rb file.

**Comment by laran** [comment]
Same problem here.

**Comment by densone** [comment]
I fixed this issue last week on my laptop. It was a real pain the ass. 

1) uninstall mysql from your mac.  
2) install mysql for osx 10.5 (I know you are using 10.6)
http://dev.mysql.com/downloads/mysql/ <-- Scroll down for 10.5
3) Compile the mysql gem with 64 bit support.  This is really important. Trust me it will not work if your mess around. 
sudo env ARCHFLAGS="-arch x86_64" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config

Your shit should now be setup and you should feel a lot better about getting some work done.

**Comment by zealoushacker** [comment]
FYI... AFAIK the `mysql` gem is no longer maintained by its author, and has been deprecated. The proper gem to be using is `ruby-mysql`.

Thus, the proper command to run for step 3 is:
`sudo env ARCHFLAGS="-arch x86_64" gem install ruby-mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config`

Obviously, before running the above, make sure to:
`sudo gem uninstall mysql` to remove the old one.
