### ISSUE TITLE
Read-only file system error when pushing to heroku

### ISSUE THREAD

**Issue by pnutus** [ricardochimal/taps#48]
Using the `heroku db:push` command, I get a code 500 from the server, and error:

<pre>
m90-130-201-189:sample_app pnutus$ heroku db:push
Loaded Taps v0.3.12
Auto-detected local database: sqlite://db/development.sqlite3
Warning: Data in the app 'high-ocean-35' will be overwritten and will not be recoverable.
Are you sure you wish to continue? (y/n)? y
Sending schema
Schema:        100% |==========================================| Time: 00:00:04
Sending indexes
users:         100% |==========================================| Time: 00:00:00
schema_migrat: 100% |==========================================| Time: 00:00:00
microposts:    100% |==========================================| Time: 00:00:00
Sending data
3 tables, 103 records
users:           0% |                                          | ETA:  --:--:--
Saving session to push_201009142336.dat..
!!! Caught Server Exception
HTTP CODE: 500
Taps Server Error: Read-only file system - dump.20359.dat
./lib/taps/data_stream.rb:194:in `initialize'./lib/taps/data_stream.rb:194:in `open'./lib/taps/data_stream.rb:194:in `parse_encoded_data'./lib/taps/data_stream.rb:152:in `fetch_remote_in_server'./lib/taps/server.rb:55:in `POST /sessions/:key/push/table'./lib/taps/db_session.rb:15:in `conn'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sequel-3.15.0/lib/sequel/database/connecting.rb:74:in `connect'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sequel-3.15.0/lib/sequel/core.rb:119:in `connect'./lib/taps/db_session.rb:14:in `conn'./lib/taps/server.rb:52:in `POST /sessions/:key/push/table'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `route'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `instance_eval'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:521:in `route_eval'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:500:in `route!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `catch'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:497:in `route!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `each'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:476:in `route!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:601:in `dispatch!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `instance_eval'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `catch'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:566:in `invoke'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:411:in `call!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/auth/basic.rb:25:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:1005:in `synchronize'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/sinatra-1.0/lib/sinatra/base.rb:979:in `call'/home/heroku_rack/lib/static_assets.rb:9:in `call'/home/heroku_rack/lib/last_access.rb:25:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/urlmap.rb:47:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in `each'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/urlmap.rb:41:in `call'/home/heroku_rack/lib/date_header.rb:14:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/rack-1.1.0/lib/rack/builder.rb:77:in `call'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:76:in `pre_process'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:74:in `catch'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:74:in `pre_process'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:57:in `process'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/connection.rb:42:in `receive_data'/usr/ruby1.8.7/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'/usr/ruby1.8.7/lib/ruby/gems/1.8/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/backends/base.rb:57:in `start'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/server.rb:156:in `start'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/controllers/controller.rb:80:in `start'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/runner.rb:177:in `send'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/runner.rb:177:in `run_command'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/lib/thin/runner.rb:143:in `run!'/home/slugs/150602_f9cc766_44dc/mnt/.gems/gems/thin-1.2.7/bin/thin:6/usr/ruby1.8.7/bin/thin:19:in `load'/usr/ruby1.8.7/bin/thin:19
</pre>

Why is taps trying to save a dump to my slug? Shouldn't it just put the data in the database? (I'm guessing that's what's causing the error.)

I am using rvm, ruby 1.9.2-p0, taps 0.3.12 and heroku 1.10.2.

**Comment by ricardochimal** [comment]
give it another shot but I haven't tested with ruby 1.9.2 yet, I'll be getting to that soon.  If it doesn't work try with ruby 1.8.7

**Comment by pnutus** [comment]
Now I'm getting the `instance of DateTime needs to have method 'marshal_load'`error. That's 1.9.2, isn't it?

**Comment by ricardochimal** [comment]
yeah that's 1.9.2, I marshal DateTime but there's some difference in how 1.9.2 does marshalling for DateTime objects.  Until I get a good solution for that 1.9.2 won't work yet.

That shouldn't keep you from using 1.9.2 on a daily basis though, since you can use rvm to have 1.8.7 with the heroku and taps gems and switch back and forth between 1.8.7 and 1.9.2.

**Comment by pnutus** [comment]
Thanks for the quick replies! I already use rvm, and it's pretty painless.
