### ISSUE TITLE
CWD needs be writeable for tabs.db

### ISSUE THREAD

**Issue by kmayer** [ricardochimal/taps#5]
The current working directory where you start up the taps server must be read/writable so the server can create the sqlite://tabs.db file. This is not always the case. I got a very confusing warning:

  <code>/Library/Ruby/Gems/1.8/gems/sqlite3-ruby-1.2.5/lib/sqlite3/errors.rb:62:in `check': SQLite3::CantOpenException could not open database: unable to open database file (Sequel::DatabaseConnectionError)</code>

(i.e. To recreate, cd to a read-only directory, then try to start up a taps server)

So, perhaps add a startup check to make sure :taps_database_url is writeable (and print out a warning if it is not), or have the url point, instead, to a temp directory.

**Comment by ricardochimal** [comment]
should be fixed
