### ISSUE TITLE
Rails 3 + Heroku push = Sequel cannot connect

### ISSUE THREAD

**Issue by ghost** [ricardochimal/taps#52]
Hi,
I have taps (0.3.13) & sequel (3.15.0) & mysql2 (0.2.4) in with a Rails3 app in linux. I try and do "heroku db:push" and get the error message:

```
Failed to connect to database:
  Sequel::AdapterNotFound -> LoadError: no such file to load -- mysql2
```

I do have mysql2 - project works great locally. Any ideas what to try?

**Comment by ricardochimal** [comment]
I tested that mysql2 works with 0.3.14
