### ISSUE TITLE
Rack Dependency

### ISSUE THREAD

**Issue by delmendo** [ricardochimal/taps#57]
Rails 2.3.9 now seems to require rack 1.1.0 or higher - any plans to upgrade taps to run with a newer version of rack?

**Comment by ricardochimal** [comment]
The dependency is specified as >= 1.0.1 so it should already work fine.

**Comment by economysizegeek** [comment]
Yeah sorry about that - I found out later that the order in the Gemfile matters (I thought it was figuring out dependencies holistically) :) Sorry for the stray bug report
