### ISSUE TITLE
Problem with Ruby 1.9.2

### ISSUE THREAD

**Issue by michaltaberski** [ricardochimal/taps#65]
I tried to use taps, and I had a problem with Ruby 1.9.2 on a client side. When I changed to 1.8.7 (default system ruby) everything works fine. 
The problem has following content: 

chema:         82% |==================================        | ETA:  00:00:07
Schema:         85% |===================================       | ETA:  00:00:05
Schema:         88% |====================================      | ETA:  00:00:04
Schema:         91% |======================================    | ETA:  00:00:03
Schema:         94% |=======================================   | ETA:  00:00:02
Schema:         97% |========================================  | ETA:  00:00:01
Schema:        100% |==========================================| Time: 00:00:40
Receiving data
34 tables, 6,800 records
Error encountered loading data, wrote the data chunk to dump.26376.dat --:--:--
/Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/data_stream.rb:192:in `load': class DateTime needs to have method`_load' (TypeError)
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/data_stream.rb:192:in `parse_encoded_data'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/data_stream.rb:135:in`fetch_remote'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:299:in `block in pull_data_from_table'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:292:in`loop'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:292:in `pull_data_from_table'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:275:in`block in pull_data'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:269:in `each'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:269:in`pull_data'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:244:in `block in run'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:194:in`call'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:194:in `catch_errors'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/operation.rb:237:in`run'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/cli.rb:169:in `clientxfer'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/cli.rb:38:in`pull'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/lib/taps/cli.rb:26:in `run'
    from /Users/tesla/.rvm/gems/ruby-1.9.2-p0/gems/taps-0.3.14/bin/taps:6:in`<top (required)>'

**Comment by adrianpike** [comment]
I'm also having a similar problem. I'm running 1.8.7 REE on the server, and 1.9.2 on the client.

Error encountered loading data, wrote the data chunk to dump.17248.dat
TypeError - instance of DateTime needs to have method `marshal_load':
 /opt/ruby-enterprise-1.8.7-2011.03/lib/ruby/gems/1.8/gems/taps-0.3.23/bin/../lib/taps/data_stream.rb:192:in`load'

**Comment by cmaujean** [comment]
I  hacked around this problem by running 1.9.2 on the server in an rvm sandbox:
- create a user on the server
- install rvm as that user, locally # avoid blowing up your application
- rvm install 1.9.2
- rvm rubygems latest
- rvm use 1.9.2@tapsserver --create
- install taps (and any supporting gems like mysql or postgresql gems)
- run taps server as usual
