### ISSUE TITLE
Error encountered loading data (Ruby 1.9)

### ISSUE THREAD

**Issue by pedro** [ricardochimal/taps#7]
Originally reported by bmaland on the heroku client issues:

During `heroku db:pull`, I get the following error on my Ruby 1.9 system:

```
Error encountered loading data, wrote the data chunk to dump.10718.gz              | ETA:  --:--:--
/usr/local/lib/ruby/gems/1.9.1/gems/taps-0.2.18/lib/taps/client_session.rb:232:in `load': class Date needs to have method `_load' (TypeError)
```

It does work fine with Ruby 1.8.6 so it's probably some compatibility issue.

**Comment by ricardochimal** [comment]
both end points need to be using a similar ruby version at the moment, because we don't have ruby 1.9 on heroku it will not unmarshal properly

**Comment by VetriVellore** [comment]
I get the same error with 1.8.7 - does it work only with Ruby 1.8.6?

**Comment by fermion** [comment]
I'm seeing this today.

My stack:

rsterner$ heroku stack
  aspen-mri-1.8.6
  bamboo-ree-1.8.7
- bamboo-mri-1.9.1

My local system:

rsterner$ ruby -v
ruby 1.9.1p376 (2009-12-07 revision 26041) [i386-darwin10.2.0]

See anything obvious?  I don't.

Thanks!

**Comment by ricardochimal** [comment]
You need to be running heroku db:push w/ ruby 1.8 right now.  Taps marshals the data for speed (json / yaml is slow) and so requires a compatible marshal format.  The stack that your application runs in does not affect this requirement since the taps heroku endpoint itself runs on ruby 1.8.

**Comment by fermion** [comment]
Heya, thanks for the quick reply.  I'd thought to try 1.8.7 shortly after posting the comment but got:

MySQL server has gone away (Mysql::Error)

Updating to the latest taps/sequel gems seemed to fix it.

Thanks again!
