### ISSUE TITLE
primary_key 'id' columns being detected as :type=>String

### ISSUE THREAD

**Issue by rcreasey** [ricardochimal/taps#73]
Forgive me if this is a sequel issue, but it seems when trying to do a db:pull from a mysql db to another mysql db, I'm getting the following errors:

https://gist.github.com/823900

It appears that the remote table's schema is being translated incorrectly.  primary_key 'id' columns are being identified as :type=>String, which causes a problem when trying to load the data to the local database.  

If this is indeed a sequel library problem, let me know and I'll create the issue on their page.

**Comment by ricardochimal** [comment]
Just trying to clarify, your id column is varchar(255) ?  or is it an integer and it's incorrectly thinking it is a string?

**Comment by rcreasey** [comment]
Sorry, I guess I should have put the actual remote table's structure in that gist.  It's been updated.

It's a:
| ID                  | bigint(20) unsigned | NO   | PRI | NULL                | auto_increment | 

And when pulling it down it's trying to make it into a String.

Hrm, could this be the problem:

sequel-0.3.17/lib/sequel/extensions/schema_dumper.rb#121 ?

It seems it doesn't regex match bigint.  The remote database is an AWS RDS "mysql" db, so I'm not sure if the ID column is being enforced as an bigint, or that's just how RDS handles its ID primary key columns.  Either way, this looks like it is confirming it as being sequel incorrectly telling taps the remote db schema?

**Comment by rcreasey** [comment]
(sorry, didn't mean to close this yet)

**Comment by ricardochimal** [comment]
Ah I see, the problem is in the regex for bigint in line 125 of schema_dumper, it needs to be able to match unsigned as well.

**Comment by rcreasey** [comment]
Awesome.  That totally fixed the primary key problem.  I'm going to fork sequel and suggest the pull request for it.

What about these errors?

class DateTime needs to have method `_load' ?

**Comment by ricardochimal** [comment]
I think you'll need to use rvm to run taps under ruby 1.8.7, it has some problems right now under 1.9.x.  Once you get that going it should work fine.

**Comment by rcreasey** [comment]
Cool, thanks for your help.

I've submitted a pull request to sequel and hopefully this'll get merged into 0.3.21.

**Comment by rcreasey** [comment]
Christ, I mean sequel-3.21.0.  

I need to lay off the coffee.
