### ISSUE TITLE
undeclared dependency on hoptoad_notifier

### ISSUE THREAD

**Issue by alexch** [ricardochimal/taps#75]
"taps server" apparently depends upon hoptoad_notifier, but that dependency isn't declared in the gemspec.

symptom: no such file to load -- hoptoad_notifier

workaround: [sudo] gem install hoptoad_notifier

Not sure if the solution is to add the dependency or remove the code (or make it fall back gracefully).

**Comment by ddollar** [comment]
Gems that are specific to the "server" component are only defined in the Gemfile, in the :server group. The .gemspec dependencies are only for the client.

Cheers,
David

**Comment by alexch** [comment]
Fair enough, but then consider this a documentation bug. Please amend the readme to include the appropriate bundler command line.

Actually, wait a second -- is there an appropriate bundler command line? Where's the Gemfile? If I do "gem install taps" on my server then I'm probably nowhere near the gem install dir that has the Gemfile, so bundler won't work. 

I think maybe you need to add the dependency to the gemspec after all. Or add "gem install hoptoad_notifier" to the readme.

**Comment by ddollar** [comment]
I updated the README with new instructions for starting a server.

**Comment by alexch** [comment]
Kudos for the instant gratification, but really? You'd rather have users jump through all those git and bundler hoops rather than just stick a "gem install hoptoad_notifier" in there?

**Comment by ddollar** [comment]
Moved the hoptoad_notifier require into a rescue with notification, and moved back to the old server start instructions.

Thanks for the feedback!

**Comment by alexch** [comment]
Yippee! :-)
