### ISSUE TITLE
doc: please clarify Foreign Keys issue

### ISSUE THREAD

**Issue by alexch** [ricardochimal/taps#76]
The README says "Known Issues: Foreign Keys get lost in the schema transfer".

This is confusing to me, since a foreign key is a field in one table that matches the primary key of another table. These fields all seem to get transferred fine. So to what is the README referring? 

Are you actually talking about foreign key constraints? And if so, how do you recommend we put them back into the schema?

**Comment by ddollar** [comment]
Yes, it means foreign key constraints. I will update the documentation.

We have not figured out a good way to do these cross-database yet. If you have a good idea, I'd definitely take a look at a pull request.

Cheers,
David

**Comment by alexch** [comment]
I don't have a _good_ idea but maybe point to some other docs like http://jjinux.blogspot.com/2009/08/rails-foreign-key-constraints.html or http://stackoverflow.com/questions/320194/support-for-foreign-key-constraint-in-rails

I will say that knowing it's just the constraints that don't work is a load off my mind, since after seeing that note I feared that you'd done something really naive like renumbering ids. Thankfully, you are smart :-)

BTW taps + heroku = migratory bliss.

**Comment by alexch** [comment]
see also https://github.com/matthuhiggins/foreigner for inspiration (it uses ActiveRecord, not Sequel but has adapters that include raw SQL to find and add FKCs for several DBMSs)

**Comment by drewcrawford** [comment]
This issue is marked as "closed", however Heroku's [documentation](http://devcenter.heroku.com/articles/taps) on Taps says:

> Taps does not support pulling or pushing foreign keys. If you need foreign keys you will need to manually recreate these.

Which gave me the same confusion as the original commenter.

Not sure if this is the right place to report.
