### ISSUE TITLE
Dates before 1970

### ISSUE THREAD

**Issue by eggie5** [ricardochimal/taps#8]
I'm moving a mysql db to postgres and when I try to transfer any dates before 1970 it crashes with this message:

C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/core.rb:156:in `string_to_datetime': Invalid Time value 'Sequel' (time out of range)
(Sequel::InvalidValue)
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:97
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:322:in`call'
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:322:in `fetch_rows'
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:320:in`each'
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:320:in `fetch_rows'
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:318:in`times'
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:318:in `fetch_rows'
        from C:/Ruby/lib/ruby/gems/1.8/gems/sequel-3.0.0/lib/sequel/adapters/postgres.rb:148:in`execute'
         ... 23 levels...
        from C:/Ruby/lib/ruby/gems/1.8/gems/heroku-1.4/bin/../lib/heroku/command.rb:11:in `run'
        from C:/Ruby/lib/ruby/gems/1.8/gems/heroku-1.4/bin/heroku:14
        from C:/Ruby/bin/heroku:19:in`load'
        from C:/Ruby/bin/heroku:19

Any ideas?

**Comment by shayfrendt** [comment]
Gettin the same thing here when moving a mysql database to mysql database:

<pre>
Sequel::InvalidValue - Invalid Time value 'Sequel' (argument out of range):
 /home/deploy/.gem/ruby/1.8/gems/sequel-3.0.0/lib/sequel/core.rb:156:in `string_to_datetime'
</pre>

**Comment by rad182** [comment]
^^ same im getting this error also

**Comment by aukevs** [comment]
Same here, can't seem to figure out how to solve this:

Error encountered loading data, wrote the data chunk to dump.2168.dat  --:--:--
c:/Ruby/lib/ruby/gems/1.8/gems/taps-0.3.2/lib/taps/data_stream.rb:183:in `_load': time out of range (ArgumentError) from c:/Ruby/lib/ruby/gems/1.8/gems/taps-0.3.2/lib/taps/data_stream.rb:183:in`load'

**Comment by mildavw** [comment]
Similar: When I push I get this:

```
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/time.rb:180:in `utc': ArgumentError: time out of range (Sequel::InvalidValue)
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/time.rb:180:in `make_time'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/time.rb:243:in `parse'
from /Library/Ruby/Gems/1.8/gems/sequel-3.10.0/lib/sequel/core.rb:215:in `string_to_datetime'
from /Library/Ruby/Gems/1.8/gems/sequel-3.10.0/lib/sequel/timezones.rb:74:in `convert_input_timestamp'
from /Library/Ruby/Gems/1.8/gems/sequel-3.10.0/lib/sequel/timezones.rb:145:in `convert_timestamp'
from /Library/Ruby/Gems/1.8/gems/sequel-3.10.0/lib/sequel/timezones.rb:29:in `database_to_application_timestamp'
from /Library/Ruby/Gems/1.8/gems/sequel-3.10.0/lib/sequel/adapters/sqlite.rb:43:in `connect'
from /Library/Ruby/Gems/1.8/gems/sqlite3-ruby-1.2.5/lib/sqlite3/translator.rb:47:in `call'
 ... 37 levels...
from /Library/Ruby/Gems/1.8/gems/heroku-1.9.9/lib/heroku/command.rb:20:in `run'
from /Library/Ruby/Gems/1.8/gems/heroku-1.9.9/bin/heroku:13
from /usr/bin/heroku:19:in `load'
from /usr/bin/heroku:19
```

**Comment by ricardochimal** [comment]
try taps 0.3.6, it should work.
