### ISSUE TITLE
Sqlite dependency

### ISSUE THREAD

**Issue by cnk** [ricardochimal/taps#84]
Is there any way to install taps without sqlite3 support? I am on an old CentOS 5 box (so we can run Oracle) and my sqlite is older than the sqlite3-ruby gem wants to support. I really don't want to fight with CentOS to upgrade a database I don't use just so I can transfer data from my local Postgresql instance to Heroku.

**Comment by edraut** [comment]
This is also stopping me from installing taps on a fairly recent ubuntu server. When attempting to install the taps gem I get the error:

```
gcc -I. -I. -I/opt/ruby-enterprise-1.8.7-2011.01/lib/ruby/1.8/x86_64-linux -I. -DHAVE_SQLITE3_COLUMN_DATABASE_NAME -DHAVE_SQLITE3_ENABLE_LOAD_EXTENSION -DHAVE_SQLITE3_LOAD_EXTENSION    -fPIC -g -O2    -c statement.c
statement.c: In function 'bind_param':
statement.c:268: error: 'sqlite3_int64' undeclared (first use in this function)
```

**Comment by technomancy** [comment]
This is also a problem for the heroku toolbelt; we can't bundle taps on OS X since it won't install without a compiler and dev headers.

**Comment by technomancy** [comment]
It looks like sqlite is only used when `DATABASE_URL` is not set. Would it be possible to remove the hard gem dependency and only load it on-demand in the fallback case?
